### ISSUE TITLE
Camera tilt on non-linear  turning

### ISSUE THREAD

**Issue by MajorLunaC** [iamgreaser/iceball#136]
I noticed the player camera tilts when you turn in a non-linear way, such as turning diagonally, or moving the cursor up or down while turning. This kind of makes me dizzy, and may cause motion sickness after a while. Could use a normal turning motion.

**Comment by rakiru** [comment]
There is an option that servers can set (MODE_DRUNK_CAM or something. I personally hate this too. It is in there because it was original an early AoS clone, but I couldn't play too long with that without feeling a bit off. Ideally, I'd prefer this was made a client option, and default to off. It just doesn't make sense to move like that.

**Comment by LeComm** [comment]
I think one does feel like that when in the corresponding psych condition (I don't mean drunk/high).
Idk if others feel so too, but somehow the drunk cam in iceball looks completely ugly to me, while I am fine with the ones in vxw and AoS .54

**Comment by iamgreaser** [comment]
Verdict: There are people who want it off and nobody I've asked insists on having it on by default. So the default is now OFF.

As a verdict is reached, this issue is now closed.
