### ISSUE TITLE
Migrate to SDL2

### ISSUE THREAD

**Issue by dany-on-demand** [iamgreaser/iceball#158]
Sigh... okay might as well just do it, enough putting it off.

https://wiki.libsdl.org/MigrationGuide

**Comment by Ericson2314** [comment]
So I hear there is a dual mouse thing for SDL2. Split screen would be cool.

**Comment by Dany0** [comment]
I've gotten to a point where I show an SDL window but I'm having issue. Would be nice if you could stop by the IRC!

**Comment by iamgreaser** [comment]
Last time I checked, multiple input was only "is this the touch pad or is this a mouse", rather than the sheer awesomeness of having two kb+mouse combos in Xi2.

**Comment by rakiru** [comment]
I think the multiple mouse thing was a 3rd-party module or something (from what I remember when reading a blog post or wiki page).

**Comment by iamgreaser** [comment]
It was all going fine until we hit input.

SDL2 builds work fine in all other areas from what I gather.

I'll explain what's needed:

*We need to remap the SDL2 keysyms to SDL1.2 keysyms as the game code relies on this.
*SDL_TEXTEVENT may be an option for international keyboard support, but due to the nature of Iceball we have to have text events being generated ALL THE TIME. In some cases this will pop open an onscreen keyboard, to which I say fuck those people, they can suffer.
*The problem with SDL_TEXTEVENT however is that we'd then have to call hook_key I think 3 times on press (still 1 time on release) - one pressing a button and a dud uni value, one pressing a dud button and the valid uni value, and one releasing the dud button and valid uni value. It also has the potential to fuck up key repeat, unless that's handled in SDL as opposed to the engine.
*If we don't go with SDL_TEXTEVENT, we'll probably have to assume a US layout and go back to square 1 again.

**Comment by rakiru** [comment]
>to which I say fuck those people, they can suffer.

Eh, so basically, fuck anyone not using English or similar alphabet? We should really support proper text input, although I'm not really sure how to go about that in a way that would also work with SDL 1. Surely it's possible to handle text similar to SDL 1 for a temporary workaround though?

As an aside, what are the reasons for continuing support for SDL 1?

**Comment by iamgreaser** [comment]
Mostly so we can have a transition period or something like that. I've also yet to chuck the latest SDL2 into my winlibs.

**Comment by fkaa** [comment]
Fixed in https://github.com/iamgreaser/iceball/pull/226
