### ISSUE TITLE
We have no old fashioned map_render

### ISSUE THREAD

**Issue by iamgreaser** [iamgreaser/iceball#176]
Proposed API:

* client.inhibit_map_autorender(enabled) - When enabled, prevent the current map from being automatically drawn at the start of each frame.
* client.inhibit_map_side_shading(map, enabled) - When enabled, disable per-side shading.
* client.inhibit_map_ao(map, enabled) - When enabled, disable ambient occlusion.
* client.map_render(map, px, py, pz, tex = nil, afmt = nil, alpha = 1.0) - Render a map globally at a given offset (px, py, pz).
* client.map_set_render_format(map, fmt) - Sets the vertex array format for a map, loosely following the VA format string. To be properly defined, but should have some extra niceties such as block types and indexed normals.

**Comment by Dany0** [comment]
That's quite a large API overhaul, but I welcome it.

**Comment by rakiru** [comment]
Why inhibit? I've always found it weird to have to enable a disable option, rather than just disable an option. The default state can be whatever - I don't see the sense of having seemingly arbitrary API methods because of old assumptions. Default settings make far more sense: they provide a consistent API (all methods are true=enable, false=disable) and work just the same regarding backwards compatibility.

**Comment by iamgreaser** [comment]
Good point, I'll redo that:

*client.map_enable_autorender(enabled) - Draw the current map at the start of each frame.
*client.map_enable_side_shading(map, enabled) - Enable per-side shading.
*client.map_enable_ao(map, enabled) - Enable ambient occlusion.

**Comment by iamgreaser** [comment]
All functions except map_set_render_format have some implementation, although alpha and texturing need work, and they don't behave amazingly well when you give them a decent-sized offset.
