### ISSUE TITLE
Add screenshot functionality

### ISSUE THREAD

**Issue by sillesta** [iamgreaser/iceball#184]
The ability to save the screen contents to a file is always nice. Maybe mapped to some function key (f2, f3?). Should it save to clsave or somewhere else? What file name should it have? (eg. `YYYY-MM-DD-HH-MM-ss.ext`). What format should it save to? (png, tga etc.)

**Comment by rakiru** [comment]
I'd definitely say PNG.

**Comment by iamgreaser** [comment]
I'd say add an API thing and dump the screenshots in clsave/vol/.

For PNG, it should be fine to just use the same filter mode for each scanline. Mode 3 (difference against average of left and top) and Mode 4 (Paeth predictor) are both pretty good overall. If you're feeling slack, Mode 0 (unfiltered) works.

Should probably just use 8bpc colour mode 6 (32bpp incl alpha) just because it'll be easier - it'll probably need a red-blue swap but we aren't exactly going to be compressing these *really really well*, are we?
