### ISSUE TITLE
Connecting to servers will usually result in the game hanging

### ISSUE THREAD

**Issue by 10se1ucgo** [iamgreaser/iceball#198]
Joining a server will most of the time make you stuck at a skyish colored screen and freeze.

*usually* Does not happen on local servers.

**Comment by rakiru** [comment]
I also get this. When joining specific servers, the game will *usually* appear to hang, and stop responding. I think it may very occasionally straight up crash, but that's only happened to me once, if ever, so I'm not sure. I can attach to the game with Decoda and watch as the Lua code still runs, so it appears to get stuck in the main client loop for some reason and never return control to the engine, meaning the screen doesn't get updated and the message queue doesn't get flushed (the latter being what Windows deems "not responding").

I get this on a remote server (`-c`) but not a local server (`-s`) running the exact same version. Disabling all mods has no effect. As of right now, I can connect to grease's test server (US West) but not my test server (EU).

I haven't labelled it as `base game` or `engine` because I'm not entirely sure if it's actually just the base game.

Using 0.2.1-26 on Windows 7 x64, built with gcc version 4.6.2 (MinGW x86).

**Comment by 10se1ucgo** [comment]
On Mesa I was able to see a little bit of the map as well actually.

**Comment by Warp00** [comment]
This does happen to me, but I can't always reproduce it. (Win8.1x64) Seems to hang for only about 10 seconds, then start working again. Sometimes however it will come up with "Not Responding", crash & burn.

**Comment by rakiru** [comment]
Well, apparently both grease's server and mine are on the same commit (4b1386939c6152d33244531708d201f82d52cc01), so fuck knows.

**Comment by 10se1ucgo** [comment]
Setting the max fps to 60 or below will allow you to work around this issue

**Comment by rakiru** [comment]
Fixed. I had one of those "AHA!" moments the other night while away from my computer. Just got around to actually seeing if it was the problem, and yes it was. Setting the frame limiter to something low would workaround the issue.
