### ISSUE TITLE
New command /quit

### ISSUE THREAD

**Issue by Chameleonhider** [iamgreaser/iceball#218]
When you get kicked or axed connection, if you're fullscreen, you have to open task manager and kill Iceball.
Having a universal, bind-able command "quit" would be very useful. This command can be used at anytime, but only by client itself - server cannot force client to quit (but can kick). I recommend default value "Home" which is 278 key.

**Comment by iamgreaser** [comment]
I solve this problem by not playing in fullscreen.

Also, when you get kicked you should be able to quit just by pressing ESC. The code even suggests this and if it turns out to not make you quit then it's a bug in the "sandbox VM" code.

**Comment by rakiru** [comment]
@iamgreaser That's not exactly a solution. :P

I'm pretty sure escape works, but I run in windowed mode too since fullscreen is exclusive fullscreen rather than borderless window, so I may just click the X without noticing.

Either way, yeah, the escape key should be made to quit if it doesn't. We don't need a new command for it, since A) commands are server-side things, and B) chat doesn't exist when kicked. Marking as bug.

**Comment by iamgreaser** [comment]
Whoops, turns out there is a bug in that handler. Fixing...
