### ISSUE TITLE
Clean up root directory

### ISSUE THREAD

**Issue by fkaa** [iamgreaser/iceball#227]
The root directory of the repo currently hogs a lot of vertical space and could use some trimming. Could we move all things related to build/packaging to its own directory (eg. xlibinc is stupid, but keep makefiles/cmake in root).

Probably a bunch of other stuff that could go away too.

**Comment by rakiru** [comment]
+1

**Comment by iamgreaser** [comment]
:+1:

**Comment by fkaa** [comment]
Not really familiar with the Makefile stuff, so not sure what can go and what can't. Anywho, here's my attempt of what could be purged!

* `buildenv/` – Seems to have been used for visual studio solution creation, which is now handled by CMake.
* `heart/` – Seems to be related to.. heartbeats? maybe this could go into `msrc/` which i think is for the server stuff?
* `osx-package-files/` – We could have a directory for deployment (packaging & making a release build).
* `tools/` – Filled with model files & few python files. Maybe we can move these to another repo? (hello, iceball org!)
* `xlibinc/` – Used for putting sackit in. Silly. Should be installed to the path instead.
* `LICENCE-*` – Do we really have that many licenses?
* `bigzipdist.sh` – Same as `osx-package-files/`.
* `findlua.sh` – Makefile cruft.
* `genmanual.py` – Move to `docs/`.
* `iblauncher.c` – Should be in the main game probably? Not like users will have other use for `iceball://`.
* `iceball-icon.xcf` – Same as `osx-package-files/`.
* `iceball.ico` – Same as `osx-package-files/`.
* `opencmd.bat` – No.
* `package-osx.sh` – Same as `osx-package-files/`.
* `pmfedit.bat` – Should really be an option inside the launcher.
* `render.old1` – Remove, will still be in history.
* `url-set-unix-gnome.sh` – Same as `osx-package-files/`.
* `wmklauncher.sh` – No.
* `zipdist.sh` – Same as `osx-package-files/`.

**Comment by 10se1ucgo** [comment]
Should mapedit have the same fate as pmfedit?

**Comment by rakiru** [comment]
* `buildenv` - Can be removed, but the wiki should have examples for building for VS (and other things).
 * `heart` - This is the master server (currently running [here](http://magicannon.com:27790/)). It could perhaps be moved to a different repo if we had a github organisation, since nobody else really needs it, but there's no better place for it currently.
 * A deployment folder sounds like a good idea.
 * `tools` - Yeah, separate repo in iceball org would perhaps be best, but no better place in current repo for it.
 * `xlibinc` - It's a bit weird having a separate folder purely for sackit. On Windows with Makefiles, everything else is in `winlibs`, and on Unix, they're in the path. This is up to grease to change though, since he's the one using the makefiles.
 * `LICENSE-*` - Engine is GPLv3, Lua code is LGPLv3, and there is some stuff from SDL in the Lua code, which is LGPLv2. It's explained at the bottom of the readme.
 * `iblauncher.c` - This registers Iceball as the handler for `iceball://` URLs on Windows. This is something that should really be in the main game, and is outdated anyway (still asks about GL/Software renderer and ENet/TCP). But...
 * `url-set-unix-gnome.sh` - Same as above, but specific to a DE rather than an OS. Is this still something that could be moved into the game?
 * mapedit.bat` - Same as `pmfedit.bat`

**Comment by iamgreaser** [comment]
I'd still keep opencmd.bat but the other bat files can seriously just die in a fire right now.

`wmklauncher.sh` IIRC is actually for building `iblauncher.c`.

Personally I'm not keen on having the protocol registration stuff in the engine. I seriously don't want the engine to touch the registry or any system stuff. I'd rather have iblauncher.c brought up to date and probably renamed as it's not actually a launcher but a protocol handler setup tool.

`url-set-unix-gnome.sh` is still somewhat experimental as URL handlers on Linux and whatnot are... weird. That would require more research.

It's entirely likely that most of the docs we have will need to be chucked out in favour of something that's right in front of your face and is actually up to date. Although currently `modding_*.txt` and `format_*.txt` are still relevant. The Lua-side protocol stuff is outdated, though.

`xlibinc` admittedly is pretty much a hack. Although until I learn how to install stuff properly, it's probably going to have to stay for sackit as I'm not really fond of telling people to shove things directly into their `/usr/include` and `/usr/lib/` directories.

Oh, and `msrc/` is for the old HTML manual generation stuff. I'd seriously just kill that with fire, along with `genmanual.py`. It's a throwback to the times where I was just yelling at people 24/7 after having had to put up with the worst people in the AoS community for over a year through adminning the Minit servers.

**Comment by rakiru** [comment]
The protocol registration stuff would make more sense in the installer, but... we don't have an installer.
