### ISSUE TITLE
Buggy mouse movement at low speeds

### ISSUE THREAD

**Issue by NotAFile** [iamgreaser/iceball#237]
I just pulled the newest master and noticed my mouse movement was not right.

If I move my mouse slowly, the view does not move at all, unless I go over a certain speed threshold.

I uploaded a video to demonstrate:

https://www.youtube.com/watch?v=WJ2iMUnaexM

After I minimize the terminal, I move my mouse across the entire length of my mouse pad in one smooth motion  at increasing speeds. At around 1.5cm/s, the game first registers mouse movement.

This is on Xorg 1.18.1 on debian sid

**Comment by rakiru** [comment]
When we moved to SDL 2, we encountered a weird bug where the mouse cursor wouldn't always be captured and you'd end up clicking out into another window. I think this might be an artefact of the workaround.

**Comment by iamgreaser** [comment]
Xorg 1.18.1, SDL 2.0.3, absolutely no issues here. Then again, I have a smooth 60fps.

There is a precedent for it though. On Windows, when the locked mouse gets warped to the middle, it fires another mouse motion event. We have a workaround for that but I think it's only enabled for Windows - we aren't the morons on the fixincludes project.

1. What's your SDL version?
2. What GPU are you using? **Do NOT just say "Intel Graphics", I fucking HATE it when people do that as that genuinely tells me NOTHING.**

glxinfo should be fine, but that's because it gives PCI numbers like so:

    Extended renderer info (GLX_MESA_query_renderer):
        Vendor: Intel Open Source Technology Center (0x8086)
        Device: Mesa DRI Intel(R) Sandybridge Mobile  (0x126)

Even more helpful is if you know exactly what GPU you have. I, for instance, have an Intel HD 3000.

**Comment by fkaa** [comment]
(We print this information at startup since https://github.com/iamgreaser/iceball/commit/5eed2ddc470912c6d0891bb9768de5789b20d1a5)

**Comment by NotAFile** [comment]
My GPU is a Intel Graphics [spoiler]HD 4600[/spoiler], but I doubt this is a GPU issue. I get 50 - 61fps.

The startup mentions

> OpenGL: 3.0 Mesa 11.1.2
> GLSL: 1.30
> Renderer: Mesa DRI Intel(R) Haswell Desktop 
> Vendor: Intel Open Source Technology Center

which is not that helpful.

`glxinfo`: http://pastebin.com/cqeudCAp

SDL version (the non-dev package has the same version):
> Package: libsdl2-dev
> Source: libsdl2
> Version: 2.0.4+dfsg1-2

**Comment by iamgreaser** [comment]
I'm kinda scared to upgrade to 2.0.4 just in case that's a regression that would be inflicted on me.

Anyway it's definitely not a framerate issue.

There's a lot of possible factors but I can't really pinpoint them.

See if your login manager has a failsafe mode that just opens up a basic terminal, then run Iceball from that. Do you still get the same issue? (If you want to make a .xsession file, I highly recommend using uxterm, or xterm if that's not provided.)

**Comment by NotAFile** [comment]
This seems to be solved now. I have no idea what caused it, but it's gone for me.
